In [30]:
import torch 
import torch.nn as nn


In [31]:
# inputs 
inputs = torch.tensor([1.0,2.0,3.0])

In [32]:
#nueron 
nueron = nn.Linear(in_features=3,out_features=1)


In [33]:
output = nueron(inputs)

In [34]:
output

tensor([1.9967], grad_fn=<ViewBackward0>)

In [35]:
#verify 
nueron.weight

Parameter containing:
tensor([[-0.5393,  0.3948,  0.4914]], requires_grad=True)

In [36]:
nueron.bias

Parameter containing:
tensor([0.2724], requires_grad=True)

In [39]:
verify = nueron.weight @ inputs + nueron.bias 

In [41]:
if verify == output:
    print('success')
else:
    print("failure")

success
